# Generated by Django 6.1 on 2026-08-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_text_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_text_fa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_title',
            field=models.CharField(default='AWMJA', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_alt_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_alt_fa',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
