# Generated by Django 6.1 on 2026-09-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker_fa', models.CharField(blank=True, max_length=200)),
                ('hero_kicker_en', models.CharField(blank=True, max_length=200)),
                ('hero_title_fa', models.CharField(blank=True, max_length=300)),
                ('hero_title_en', models.CharField(blank=True, max_length=300)),
                ('hero_lead_fa', models.TextField(blank=True)),
                ('hero_lead_en', models.TextField(blank=True)),
                ('hero_text_fa', models.TextField(blank=True)),
                ('hero_text_en', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='activities/hero/')),
                ('hero_image_alt_fa', models.CharField(blank=True, max_length=255)),
                ('hero_image_alt_en', models.CharField(blank=True, max_length=255)),
                ('hero_quote_fa', models.TextField(blank=True)),
                ('hero_quote_en', models.TextField(blank=True)),
                ('hero_stat_number', models.CharField(blank=True, max_length=20)),
                ('hero_stat_label_fa', models.CharField(blank=True, max_length=200)),
                ('hero_stat_label_en', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات Hero فعالیت\u200cها',
                'verbose_name_plural': 'تنظیمات Hero فعالیت\u200cها',
            },
        ),
    ]
