# Generated by Django 6.1 on 2026-09-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در فعالیت\u200cهای منتخب'),
        ),
    ]
