# Generated by Django 6.1 on 2026-09-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activity_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='شماره')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='عدد')),
                ('label_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('label_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آمار اثرگذاری فعالیت\u200cها',
                'verbose_name_plural': 'آمار اثرگذاری فعالیت\u200cها',
                'ordering': ['order', 'number'],
            },
        ),
    ]
