# Generated by Django 6.1 on 2026-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activityimpact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImpactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب فارسی')),
            ],
        ),
        migrations.AlterModelOptions(
            name='activityimpact',
            options={'verbose_name': 'تنظیمات بخش اثرگذاری فعالیت\u200cها', 'verbose_name_plural': 'تنظیمات بخش اثرگذاری فعالیت\u200cها'},
        ),
        migrations.AddField(
            model_name='activityimpact',
            name='button_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن دکمه انگلیسی'),
        ),
        migrations.AddField(
            model_name='activityimpact',
            name='button_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن دکمه فارسی'),
        ),
        migrations.AddField(
            model_name='activityimpact',
            name='kicker_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='برچسب انگلیسی'),
        ),
        migrations.AddField(
            model_name='activityimpact',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='توضیحات انگلیسی'),
        ),
        migrations.AddField(
            model_name='activityimpact',
            name='text_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات فارسی'),
        ),
        migrations.AddField(
            model_name='activityimpact',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AddField(
            model_name='activityimpact',
            name='title_fa',
            field=models.CharField(blank=True, max_length=300, verbose_name='عنوان فارسی'),
        ),
    ]
