# Generated by Django 6.1 on 2026-09-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activityimpactsettings_alter_activityimpact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityimpact',
            options={'ordering': ['order', 'number'], 'verbose_name': 'آمار اثرگذاری فعالیت\u200cها', 'verbose_name_plural': 'آمار اثرگذاری فعالیت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='activityimpactsettings',
            options={'verbose_name': 'تنظیمات بخش اثرگذاری فعالیت\u200cها', 'verbose_name_plural': 'تنظیمات بخش اثرگذاری فعالیت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='activityimpact',
            name='button_en',
        ),
        migrations.RemoveField(
            model_name='activityimpact',
            name='button_fa',
        ),
        migrations.RemoveField(
            model_name='activityimpact',
            name='kicker_en',
        ),
        migrations.RemoveField(
            model_name='activityimpact',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='activityimpact',
            name='text_fa',
        ),
        migrations.RemoveField(
            model_name='activityimpact',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='activityimpact',
            name='title_fa',
        ),
        migrations.AddField(
            model_name='activityimpactsettings',
            name='button_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن دکمه انگلیسی'),
        ),
        migrations.AddField(
            model_name='activityimpactsettings',
            name='button_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن دکمه فارسی'),
        ),
        migrations.AddField(
            model_name='activityimpactsettings',
            name='kicker_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='برچسب انگلیسی'),
        ),
        migrations.AddField(
            model_name='activityimpactsettings',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='توضیحات انگلیسی'),
        ),
        migrations.AddField(
            model_name='activityimpactsettings',
            name='text_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات فارسی'),
        ),
        migrations.AddField(
            model_name='activityimpactsettings',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AddField(
            model_name='activityimpactsettings',
            name='title_fa',
            field=models.CharField(blank=True, max_length=300, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='activityimpactsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
