# Generated by Django 6.1 on 2026-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_activityimpact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='شماره روایت')),
                ('category_fa', models.CharField(blank=True, max_length=200, verbose_name='دسته\u200cبندی فارسی')),
                ('category_en', models.CharField(blank=True, max_length=200, verbose_name='دسته\u200cبندی انگلیسی')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/stories/', verbose_name='تصویر روایت')),
                ('image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر فارسی')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر انگلیسی')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک روایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'روایت فعالیت',
                'verbose_name_plural': 'روایت\u200cهای فعالیت',
                'ordering': ['order', 'number'],
            },
        ),
    ]
