# Generated by Django 6.1 on 2026-09-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_activitystory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCTASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب فارسی')),
                ('kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب انگلیسی')),
                ('title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('text_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('text_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('primary_button_fa', models.CharField(blank=True, max_length=200, verbose_name='دکمه اصلی فارسی')),
                ('primary_button_en', models.CharField(blank=True, max_length=200, verbose_name='دکمه اصلی انگلیسی')),
                ('secondary_button_fa', models.CharField(blank=True, max_length=200, verbose_name='دکمه دوم فارسی')),
                ('secondary_button_en', models.CharField(blank=True, max_length=200, verbose_name='دکمه دوم انگلیسی')),
                ('primary_link', models.CharField(blank=True, max_length=255, verbose_name='لینک دکمه اصلی')),
                ('secondary_link', models.CharField(blank=True, max_length=255, verbose_name='لینک دکمه دوم')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات بخش اثرگذاری فعالیت\u200cها',
                'verbose_name_plural': 'تنظیمات بخش اثرگذاری فعالیت\u200cها',
            },
        ),
        migrations.AlterModelOptions(
            name='activityimpactsettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='activityimpactsettings',
            name='updated_at',
        ),
    ]
