# Generated by Django 6.1 on 2026-09-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activityctasettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityimpactsettings',
            options={'verbose_name': 'تنظیمات بخش اثرگذاری فعالیت\u200cها', 'verbose_name_plural': 'تنظیمات بخش اثرگذاری فعالیت\u200cها'},
        ),
    ]
