# Generated by Django 6.1 on 2026-09-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_activityimpactsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityctasettings',
            options={'verbose_name': 'تنظیمات CTA فعالیت\u200cها', 'verbose_name_plural': 'تنظیمات CTA فعالیت\u200cها'},
        ),
    ]
