# Generated by Django 6.1 on 2026-09-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_activityctasettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب پیش\u200cنمایش فارسی')),
                ('preview_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب پیش\u200cنمایش انگلیسی')),
                ('preview_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان پیش\u200cنمایش فارسی')),
                ('preview_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان پیش\u200cنمایش انگلیسی')),
                ('preview_text_fa', models.TextField(blank=True, verbose_name='متن پیش\u200cنمایش فارسی')),
                ('preview_text_en', models.TextField(blank=True, verbose_name='متن پیش\u200cنمایش انگلیسی')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='تصویر پیش\u200cنمایش')),
                ('preview_image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر فارسی')),
                ('preview_image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر انگلیسی')),
                ('foundation_year', models.PositiveIntegerField(default=2022, verbose_name='سال تأسیس')),
                ('foundation_label_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان سال تأسیس فارسی')),
                ('foundation_label_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان سال تأسیس انگلیسی')),
                ('hero_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب Hero فارسی')),
                ('hero_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب Hero انگلیسی')),
                ('hero_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero فارسی')),
                ('hero_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero انگلیسی')),
                ('hero_text_fa', models.TextField(blank=True, verbose_name='متن Hero فارسی')),
                ('hero_text_en', models.TextField(blank=True, verbose_name='متن Hero انگلیسی')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='تصویر Hero')),
                ('hero_image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین Hero فارسی')),
                ('hero_image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین Hero انگلیسی')),
                ('hero_badge_top_fa', models.CharField(blank=True, max_length=100, verbose_name='متن بالای نشان Hero فارسی')),
                ('hero_badge_top_en', models.CharField(blank=True, max_length=100, verbose_name='متن بالای نشان Hero انگلیسی')),
                ('hero_badge_bottom_fa', models.CharField(blank=True, max_length=100, verbose_name='متن پایین نشان Hero فارسی')),
                ('hero_badge_bottom_en', models.CharField(blank=True, max_length=100, verbose_name='متن پایین نشان Hero انگلیسی')),
            ],
            options={
                'verbose_name': 'تنظیمات درباره ما',
                'verbose_name_plural': 'تنظیمات درباره ما',
            },
        ),
    ]
