# Generated by Django 6.1 on 2026-09-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_abouthighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsettings',
            name='preview_button_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن دکمه پیش\u200cنمایش انگلیسی'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='preview_button_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن دکمه پیش\u200cنمایش فارسی'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='preview_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='لینک پیش\u200cنمایش'),
        ),
    ]
