# Generated by Django 6.1 on 2026-09-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aboutsettings_preview_button_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب فارسی')),
                ('kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب انگلیسی')),
                ('title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('intro_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی داخل بخش')),
                ('lead_fa', models.TextField(blank=True, verbose_name='متن اصلی فارسی')),
                ('lead_en', models.TextField(blank=True, verbose_name='متن اصلی انگلیسی')),
                ('text_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('text_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('highlight_name', models.CharField(blank=True, max_length=100, verbose_name='نام کوتاه')),
                ('highlight_text', models.CharField(blank=True, max_length=300, verbose_name='متن برجسته')),
            ],
            options={
                'verbose_name': 'معرفی درباره ما',
                'verbose_name_plural': 'معرفی درباره ما',
            },
        ),
    ]
