# Generated by Django 6.1 on 2026-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_aboutintroduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='شماره روایت')),
                ('date_main', models.CharField(blank=True, max_length=50, verbose_name='تاریخ اصلی')),
                ('date_sub', models.CharField(blank=True, max_length=50, verbose_name='تاریخ فرعی')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/stories/', verbose_name='تصویر روایت')),
                ('image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر فارسی')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر انگلیسی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'روایت درباره ما',
                'verbose_name_plural': 'روایت\u200cهای درباره ما',
                'ordering': ['order', 'number'],
            },
        ),
    ]
