# Generated by Django 6.1 on 2026-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aboutstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب فارسی')),
                ('kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب انگلیسی')),
                ('title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('intro_fa', models.TextField(blank=True, verbose_name='مقدمه فارسی')),
                ('intro_en', models.TextField(blank=True, verbose_name='مقدمه انگلیسی')),
                ('mission_number', models.CharField(blank=True, max_length=20, verbose_name='شماره مأموریت')),
                ('mission_label_fa', models.CharField(blank=True, max_length=100, verbose_name='برچسب مأموریت فارسی')),
                ('mission_label_en', models.CharField(blank=True, max_length=100, verbose_name='برچسب مأموریت انگلیسی')),
                ('mission_icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون مأموریت')),
                ('mission_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان مأموریت فارسی')),
                ('mission_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان مأموریت انگلیسی')),
                ('mission_lead_fa', models.TextField(blank=True, verbose_name='متن اصلی مأموریت فارسی')),
                ('mission_lead_en', models.TextField(blank=True, verbose_name='متن اصلی مأموریت انگلیسی')),
                ('mission_text_fa', models.TextField(blank=True, verbose_name='توضیحات مأموریت فارسی')),
                ('mission_text_en', models.TextField(blank=True, verbose_name='توضیحات مأموریت انگلیسی')),
                ('mission_footer_1', models.CharField(blank=True, max_length=100, verbose_name='پایین مأموریت ۱')),
                ('mission_footer_2', models.CharField(blank=True, max_length=100, verbose_name='پایین مأموریت ۲')),
                ('mission_footer_3', models.CharField(blank=True, max_length=100, verbose_name='پایین مأموریت ۳')),
                ('vision_number', models.CharField(blank=True, max_length=20, verbose_name='شماره چشم\u200cانداز')),
                ('vision_label_fa', models.CharField(blank=True, max_length=100, verbose_name='برچسب چشم\u200cانداز فارسی')),
                ('vision_label_en', models.CharField(blank=True, max_length=100, verbose_name='برچسب چشم\u200cانداز انگلیسی')),
                ('vision_icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون چشم\u200cانداز')),
                ('vision_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان چشم\u200cانداز فارسی')),
                ('vision_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان چشم\u200cانداز انگلیسی')),
                ('vision_lead_fa', models.TextField(blank=True, verbose_name='متن اصلی چشم\u200cانداز فارسی')),
                ('vision_lead_en', models.TextField(blank=True, verbose_name='متن اصلی چشم\u200cانداز انگلیسی')),
                ('vision_footer_1', models.CharField(blank=True, max_length=100, verbose_name='پایین چشم\u200cانداز ۱')),
                ('vision_footer_2', models.CharField(blank=True, max_length=100, verbose_name='پایین چشم\u200cانداز ۲')),
                ('vision_footer_3', models.CharField(blank=True, max_length=100, verbose_name='پایین چشم\u200cانداز ۳')),
            ],
            options={
                'verbose_name': 'مأموریت و چشم\u200cانداز',
                'verbose_name_plural': 'مأموریت و چشم\u200cانداز',
            },
        ),
    ]
