# Generated by Django 6.1 on 2026-09-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aboutmissionvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutVisionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='شماره')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مورد چشم\u200cانداز — About',
                'verbose_name_plural': 'موارد چشم\u200cانداز — About',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutmissionvision',
            options={'verbose_name': 'ماموریت و چشم\u200cانداز — About'},
        ),
    ]
