# Generated by Django 6.1 on 2026-09-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_aboutvisionpoint_alter_aboutmissionvision_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGoalsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب فارسی')),
                ('kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب انگلیسی')),
                ('title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('intro_fa', models.TextField(blank=True, verbose_name='مقدمه فارسی')),
                ('intro_en', models.TextField(blank=True, verbose_name='مقدمه انگلیسی')),
                ('closing_name', models.CharField(blank=True, max_length=100, verbose_name='نام پایانی')),
                ('closing_text_fa', models.TextField(blank=True, verbose_name='متن پایانی فارسی')),
                ('closing_text_en', models.TextField(blank=True, verbose_name='متن پایانی انگلیسی')),
            ],
            options={
                'verbose_name': 'تنظیمات اهداف — About',
                'verbose_name_plural': 'تنظیمات اهداف — About',
            },
        ),
    ]
