# Generated by Django 6.1 on 2026-09-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_aboutgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='عدد')),
                ('label_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان فارسی')),
                ('label_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان انگلیسی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'آمار اثرگذاری صفحه اصلی',
                'verbose_name_plural': 'آمارهای اثرگذاری صفحه اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeImpactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب فارسی')),
                ('kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب انگلیسی')),
                ('title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('text_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('text_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
            ],
            options={
                'verbose_name': 'تنظیمات اثرگذاری صفحه اصلی',
                'verbose_name_plural': 'تنظیمات اثرگذاری صفحه اصلی',
            },
        ),
    ]
