# Generated by Django 6.1 on 2026-09-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_homeimpact_homeimpactsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('excerpt_fa', models.TextField(blank=True, verbose_name='خلاصه فارسی')),
                ('excerpt_en', models.TextField(blank=True, verbose_name='خلاصه انگلیسی')),
                ('content_fa', models.TextField(blank=True, verbose_name='محتوای کامل فارسی')),
                ('content_en', models.TextField(blank=True, verbose_name='محتوای کامل انگلیسی')),
                ('category', models.CharField(choices=[('statement', 'بیانیه\u200cها'), ('activity', 'فعالیت\u200cها'), ('international', 'فعالیت بین\u200cالمللی'), ('women-rights', 'حقوق زنان')], default='statement', max_length=50, verbose_name='دسته\u200cبندی')),
                ('category_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی فارسی')),
                ('category_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='تصویر خبر')),
                ('image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر فارسی')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر انگلیسی')),
                ('published_at', models.DateField(verbose_name='تاریخ انتشار')),
                ('source', models.CharField(default='AWMJA', max_length=200, verbose_name='منبع')),
                ('source_url', models.URLField(blank=True, verbose_name='لینک منبع')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('is_featured', models.BooleanField(default=False, verbose_name='خبر ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NewsPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker_fa', models.CharField(blank=True, max_length=300, verbose_name='برچسب Hero فارسی')),
                ('hero_kicker_en', models.CharField(blank=True, max_length=300, verbose_name='برچسب Hero انگلیسی')),
                ('hero_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero فارسی')),
                ('hero_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero انگلیسی')),
                ('hero_text_fa', models.TextField(blank=True, verbose_name='توضیحات Hero فارسی')),
                ('hero_text_en', models.TextField(blank=True, verbose_name='توضیحات Hero انگلیسی')),
                ('featured_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب خبر ویژه فارسی')),
                ('featured_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب خبر ویژه انگلیسی')),
                ('featured_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان خبر ویژه فارسی')),
                ('featured_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان خبر ویژه انگلیسی')),
                ('latest_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب آخرین اخبار فارسی')),
                ('latest_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب آخرین اخبار انگلیسی')),
                ('latest_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان آخرین اخبار فارسی')),
                ('latest_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان آخرین اخبار انگلیسی')),
                ('latest_text_fa', models.TextField(blank=True, verbose_name='توضیحات آخرین اخبار فارسی')),
                ('latest_text_en', models.TextField(blank=True, verbose_name='توضیحات آخرین اخبار انگلیسی')),
                ('media_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب رسانه و منابع فارسی')),
                ('media_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب رسانه و منابع انگلیسی')),
                ('media_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان رسانه و منابع فارسی')),
                ('media_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان رسانه و منابع انگلیسی')),
                ('media_text_fa', models.TextField(blank=True, verbose_name='توضیحات رسانه و منابع فارسی')),
                ('media_text_en', models.TextField(blank=True, verbose_name='توضیحات رسانه و منابع انگلیسی')),
                ('media_note_title_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان یادداشت رسانه فارسی')),
                ('media_note_title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان یادداشت رسانه انگلیسی')),
                ('media_note_text_fa', models.TextField(blank=True, verbose_name='متن یادداشت رسانه فارسی')),
                ('media_note_text_en', models.TextField(blank=True, verbose_name='متن یادداشت رسانه انگلیسی')),
                ('archive_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب آرشیو فارسی')),
                ('archive_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب آرشیو انگلیسی')),
                ('archive_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان آرشیو فارسی')),
                ('archive_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان آرشیو انگلیسی')),
                ('archive_text_fa', models.TextField(blank=True, verbose_name='توضیحات آرشیو فارسی')),
                ('archive_text_en', models.TextField(blank=True, verbose_name='توضیحات آرشیو انگلیسی')),
                ('archive_button_fa', models.CharField(blank=True, max_length=200, verbose_name='دکمه آرشیو فارسی')),
                ('archive_button_en', models.CharField(blank=True, max_length=200, verbose_name='دکمه آرشیو انگلیسی')),
                ('archive_link', models.CharField(blank=True, max_length=500, verbose_name='لینک آرشیو')),
            ],
            options={
                'verbose_name': 'تنظیمات اخبار',
                'verbose_name_plural': 'تنظیمات اخبار',
            },
        ),
    ]
