# Generated by Django 6.1 on 2026-09-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_news_newspagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='لینک ادامه مطلب'),
        ),
    ]
