# Generated by Django 6.1 on 2026-09-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_news_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('category', models.CharField(choices=[('international', 'بین\u200cالمللی'), ('advocacy', 'دادخواهی'), ('human-rights', 'حقوق بشر'), ('meeting', 'نشست'), ('conference', 'کنفرانس'), ('other', 'سایر')], default='other', max_length=50, verbose_name='دسته\u200cبندی')),
                ('category_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی فارسی')),
                ('category_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='تصویر رویداد')),
                ('image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر فارسی')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر انگلیسی')),
                ('event_date', models.DateField(verbose_name='تاریخ رویداد')),
                ('location_fa', models.CharField(blank=True, max_length=200, verbose_name='مکان فارسی')),
                ('location_en', models.CharField(blank=True, max_length=200, verbose_name='مکان انگلیسی')),
                ('status', models.CharField(choices=[('upcoming', 'رویداد پیش\u200cرو'), ('past', 'رویداد گذشته')], default='upcoming', max_length=20, verbose_name='وضعیت رویداد')),
                ('external_url', models.URLField(blank=True, verbose_name='لینک جزئیات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='رویداد ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['-event_date', 'order'],
            },
        ),
    ]
