# Generated by Django 6.1 on 2026-09-05 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('category', models.CharField(choices=[('advocacy', 'دادخواهی'), ('meetings', 'نشست\u200cها'), ('international', 'بین\u200cالمللی'), ('empowerment', 'توانمندسازی'), ('events', 'رویدادها'), ('other', 'سایر')], default='other', max_length=50, verbose_name='دسته\u200cبندی')),
                ('category_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی فارسی')),
                ('category_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی انگلیسی')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='تصویر روی جلد آلبوم')),
                ('cover_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین جلد فارسی')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین جلد انگلیسی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آلبوم گالری',
                'verbose_name_plural': 'آلبوم\u200cهای گالری',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], default='image', max_length=20, verbose_name='نوع رسانه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='ویدیو')),
                ('title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر فارسی')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر انگلیسی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.galleryalbum', verbose_name='آلبوم')),
            ],
            options={
                'verbose_name': 'رسانه گالری',
                'verbose_name_plural': 'رسانه\u200cهای گالری',
                'ordering': ['order', 'id'],
            },
        ),
    ]
