# Generated by Django 6.1 on 2026-09-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_galleryalbum_gallerymedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='شماره مرحله')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مرحله رویکرد',
                'verbose_name_plural': 'مراحل رویکرد',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='شماره')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ارزش اصلی',
                'verbose_name_plural': 'ارزش\u200cهای اصلی',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='شماره')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مورد مأموریت',
                'verbose_name_plural': 'موارد مأموریت',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MissionVisionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب Hero فارسی')),
                ('hero_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب Hero انگلیسی')),
                ('hero_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero فارسی')),
                ('hero_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero انگلیسی')),
                ('hero_highlight_fa', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته Hero فارسی')),
                ('hero_highlight_en', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته Hero انگلیسی')),
                ('hero_text_fa', models.TextField(blank=True, verbose_name='توضیحات Hero فارسی')),
                ('hero_text_en', models.TextField(blank=True, verbose_name='توضیحات Hero انگلیسی')),
                ('mission_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب مأموریت فارسی')),
                ('mission_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب مأموریت انگلیسی')),
                ('mission_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان مأموریت فارسی')),
                ('mission_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان مأموریت انگلیسی')),
                ('mission_lead_fa', models.TextField(blank=True, verbose_name='متن اصلی مأموریت فارسی')),
                ('mission_lead_en', models.TextField(blank=True, verbose_name='متن اصلی مأموریت انگلیسی')),
                ('mission_text_fa', models.TextField(blank=True, verbose_name='متن تکمیلی مأموریت فارسی')),
                ('mission_text_en', models.TextField(blank=True, verbose_name='متن تکمیلی مأموریت انگلیسی')),
                ('mission_text_2_fa', models.TextField(blank=True, verbose_name='متن دوم مأموریت فارسی')),
                ('mission_text_2_en', models.TextField(blank=True, verbose_name='متن دوم مأموریت انگلیسی')),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='mission/', verbose_name='تصویر مأموریت')),
                ('mission_image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر مأموریت فارسی')),
                ('mission_image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر مأموریت انگلیسی')),
                ('mission_badge_title_fa', models.CharField(blank=True, max_length=100, verbose_name='عنوان نشان مأموریت فارسی')),
                ('mission_badge_title_en', models.CharField(blank=True, max_length=100, verbose_name='عنوان نشان مأموریت انگلیسی')),
                ('mission_badge_text_fa', models.CharField(blank=True, max_length=200, verbose_name='متن نشان مأموریت فارسی')),
                ('mission_badge_text_en', models.CharField(blank=True, max_length=200, verbose_name='متن نشان مأموریت انگلیسی')),
                ('vision_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب چشم\u200cانداز فارسی')),
                ('vision_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب چشم\u200cانداز انگلیسی')),
                ('vision_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان چشم\u200cانداز فارسی')),
                ('vision_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان چشم\u200cانداز انگلیسی')),
                ('vision_lead_fa', models.TextField(blank=True, verbose_name='متن اصلی چشم\u200cانداز فارسی')),
                ('vision_lead_en', models.TextField(blank=True, verbose_name='متن اصلی چشم\u200cانداز انگلیسی')),
                ('vision_text_fa', models.TextField(blank=True, verbose_name='متن تکمیلی چشم\u200cانداز فارسی')),
                ('vision_text_en', models.TextField(blank=True, verbose_name='متن تکمیلی چشم\u200cانداز انگلیسی')),
                ('vision_statement_fa', models.TextField(blank=True, verbose_name='بیانیه چشم\u200cانداز فارسی')),
                ('vision_statement_en', models.TextField(blank=True, verbose_name='بیانیه چشم\u200cانداز انگلیسی')),
                ('cta_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب CTA فارسی')),
                ('cta_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب CTA انگلیسی')),
                ('cta_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان CTA فارسی')),
                ('cta_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان CTA انگلیسی')),
                ('cta_text_fa', models.TextField(blank=True, verbose_name='توضیحات CTA فارسی')),
                ('cta_text_en', models.TextField(blank=True, verbose_name='توضیحات CTA انگلیسی')),
                ('cta_button_fa', models.CharField(blank=True, max_length=200, verbose_name='متن دکمه همکاری فارسی')),
                ('cta_button_en', models.CharField(blank=True, max_length=200, verbose_name='متن دکمه همکاری انگلیسی')),
                ('cta_button_2_fa', models.CharField(blank=True, max_length=200, verbose_name='متن دکمه دوم فارسی')),
                ('cta_button_2_en', models.CharField(blank=True, max_length=200, verbose_name='متن دکمه دوم انگلیسی')),
            ],
            options={
                'verbose_name': 'تنظیمات مأموریت و چشم\u200cانداز',
                'verbose_name_plural': 'تنظیمات مأموریت و چشم\u200cانداز',
            },
        ),
    ]
