# Generated by Django 6.1 on 2026-09-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_achievement_achievementimpact_achievementmedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='شماره هدف')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('category', models.CharField(choices=[('justice', 'عدالت'), ('education', 'آموزش'), ('equality', 'برابری'), ('protection', 'حفاظت'), ('advocacy', 'دادخواهی'), ('empowerment', 'توانمندسازی'), ('global-action', 'اقدام جهانی'), ('participation', 'مشارکت'), ('other', 'سایر')], default='other', max_length=50, verbose_name='دسته\u200cبندی')),
                ('category_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی فارسی')),
                ('category_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی انگلیسی')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='هدف شاخص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'هدف',
                'verbose_name_plural': 'اهداف',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='GoalPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب Hero فارسی')),
                ('hero_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب Hero انگلیسی')),
                ('hero_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero فارسی')),
                ('hero_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero انگلیسی')),
                ('hero_text_fa', models.TextField(blank=True, verbose_name='توضیحات Hero فارسی')),
                ('hero_text_en', models.TextField(blank=True, verbose_name='توضیحات Hero انگلیسی')),
                ('goals_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب اهداف فارسی')),
                ('goals_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب اهداف انگلیسی')),
                ('goals_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان اهداف فارسی')),
                ('goals_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان اهداف انگلیسی')),
                ('goals_text_fa', models.TextField(blank=True, verbose_name='توضیحات اهداف فارسی')),
                ('goals_text_en', models.TextField(blank=True, verbose_name='توضیحات اهداف انگلیسی')),
                ('commitment_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب تعهد فارسی')),
                ('commitment_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب تعهد انگلیسی')),
                ('commitment_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان تعهد فارسی')),
                ('commitment_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان تعهد انگلیسی')),
                ('commitment_highlight_fa', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته تعهد فارسی')),
                ('commitment_highlight_en', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته تعهد انگلیسی')),
                ('commitment_text_fa', models.TextField(blank=True, verbose_name='توضیحات تعهد فارسی')),
                ('commitment_text_en', models.TextField(blank=True, verbose_name='توضیحات تعهد انگلیسی')),
                ('cta_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب CTA فارسی')),
                ('cta_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب CTA انگلیسی')),
                ('cta_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان CTA فارسی')),
                ('cta_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان CTA انگلیسی')),
                ('cta_highlight_fa', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته CTA فارسی')),
                ('cta_highlight_en', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته CTA انگلیسی')),
                ('cta_button_fa', models.CharField(blank=True, max_length=200, verbose_name='متن دکمه CTA فارسی')),
                ('cta_button_en', models.CharField(blank=True, max_length=200, verbose_name='متن دکمه CTA انگلیسی')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه اهداف',
                'verbose_name_plural': 'تنظیمات صفحه اهداف',
            },
        ),
    ]
