# Generated by Django 6.1 on 2026-09-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_goal_goalpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='شماره عضو')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('role_fa', models.CharField(blank=True, max_length=300, verbose_name='سمت فارسی')),
                ('role_en', models.CharField(blank=True, max_length=300, verbose_name='سمت انگلیسی')),
                ('kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب فارسی')),
                ('kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب انگلیسی')),
                ('bio_fa', models.TextField(blank=True, verbose_name='بیوگرافی فارسی')),
                ('bio_en', models.TextField(blank=True, verbose_name='بیوگرافی انگلیسی')),
                ('position_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان موقعیت فارسی')),
                ('position_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان موقعیت انگلیسی')),
                ('organization', models.CharField(blank=True, default='AWMJA', max_length=100, verbose_name='سازمان')),
                ('focus_fa', models.CharField(blank=True, max_length=300, verbose_name='حوزه فعالیت فارسی')),
                ('focus_en', models.CharField(blank=True, max_length=300, verbose_name='حوزه فعالیت انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaders/', verbose_name='تصویر')),
                ('image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر فارسی')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر انگلیسی')),
                ('facebook_url', models.URLField(blank=True, verbose_name='لینک Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='لینک Twitter')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='لینک LinkedIn')),
                ('is_main', models.BooleanField(default=False, verbose_name='رهبر اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عضو رهبری',
                'verbose_name_plural': 'اعضای رهبری',
                'ordering': ['order', 'number'],
            },
        ),
    ]
