# Generated by Django 6.1 on 2026-09-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('excerpt_fa', models.TextField(blank=True, verbose_name='خلاصه فارسی')),
                ('excerpt_en', models.TextField(blank=True, verbose_name='خلاصه انگلیسی')),
                ('content_fa', models.TextField(blank=True, verbose_name='متن کامل فارسی')),
                ('content_en', models.TextField(blank=True, verbose_name='متن کامل انگلیسی')),
                ('category', models.CharField(choices=[('women-rights', 'حقوق زنان'), ('education', 'آموزش'), ('social-justice', 'عدالت اجتماعی'), ('society', 'جامعه'), ('awareness', 'آگاهی'), ('perspective', 'دیدگاه'), ('other', 'سایر')], default='other', max_length=50, verbose_name='دسته\u200cبندی')),
                ('category_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی فارسی')),
                ('category_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان دسته\u200cبندی انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر مقاله')),
                ('image_alt_fa', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر فارسی')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر انگلیسی')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='نام منبع')),
                ('source_url', models.URLField(blank=True, verbose_name='لینک منبع')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقاله منتخب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب Hero فارسی')),
                ('hero_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب Hero انگلیسی')),
                ('hero_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero فارسی')),
                ('hero_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان Hero انگلیسی')),
                ('hero_highlight_fa', models.CharField(blank=True, max_length=300, verbose_name='متن برجسته Hero فارسی')),
                ('hero_highlight_en', models.CharField(blank=True, max_length=300, verbose_name='متن برجسته Hero انگلیسی')),
                ('hero_text_fa', models.TextField(blank=True, verbose_name='توضیحات Hero فارسی')),
                ('hero_text_en', models.TextField(blank=True, verbose_name='توضیحات Hero انگلیسی')),
                ('featured_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب مقاله منتخب فارسی')),
                ('featured_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب مقاله منتخب انگلیسی')),
                ('featured_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان مقاله منتخب فارسی')),
                ('featured_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان مقاله منتخب انگلیسی')),
                ('featured_text_fa', models.TextField(blank=True, verbose_name='توضیحات مقاله منتخب فارسی')),
                ('featured_text_en', models.TextField(blank=True, verbose_name='توضیحات مقاله منتخب انگلیسی')),
                ('articles_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب مقالات فارسی')),
                ('articles_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب مقالات انگلیسی')),
                ('articles_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان مقالات فارسی')),
                ('articles_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان مقالات انگلیسی')),
                ('articles_highlight_fa', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته مقالات فارسی')),
                ('articles_highlight_en', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته مقالات انگلیسی')),
                ('articles_text_fa', models.TextField(blank=True, verbose_name='توضیحات مقالات فارسی')),
                ('articles_text_en', models.TextField(blank=True, verbose_name='توضیحات مقالات انگلیسی')),
                ('cta_kicker_fa', models.CharField(blank=True, max_length=200, verbose_name='برچسب CTA فارسی')),
                ('cta_kicker_en', models.CharField(blank=True, max_length=200, verbose_name='برچسب CTA انگلیسی')),
                ('cta_title_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان CTA فارسی')),
                ('cta_title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان CTA انگلیسی')),
                ('cta_highlight_fa', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته CTA فارسی')),
                ('cta_highlight_en', models.CharField(blank=True, max_length=200, verbose_name='متن برجسته CTA انگلیسی')),
                ('cta_text_fa', models.TextField(blank=True, verbose_name='توضیحات CTA فارسی')),
                ('cta_text_en', models.TextField(blank=True, verbose_name='توضیحات CTA انگلیسی')),
                ('cta_button_fa', models.CharField(blank=True, max_length=200, verbose_name='متن دکمه CTA فارسی')),
                ('cta_button_en', models.CharField(blank=True, max_length=200, verbose_name='متن دکمه CTA انگلیسی')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه مقالات',
                'verbose_name_plural': 'تنظیمات صفحه مقالات',
            },
        ),
    ]
