# Generated by Django 6.1 on 2026-09-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_article_articlepagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(choices=[('membership', 'عضویت در جنبش'), ('support', 'حمایت از جنبش'), ('cooperation', 'همکاری'), ('media', 'همکاری رسانه\u200cای'), ('general', 'پرسش عمومی'), ('other', 'سایر موارد')], max_length=50)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('replied', 'پاسخ داده شد'), ('closed', 'بسته شد')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker_fa', models.CharField(blank=True, max_length=200)),
                ('hero_kicker_en', models.CharField(blank=True, max_length=200)),
                ('hero_title_fa', models.CharField(blank=True, max_length=300)),
                ('hero_title_en', models.CharField(blank=True, max_length=300)),
                ('hero_highlight_fa', models.CharField(blank=True, max_length=300)),
                ('hero_highlight_en', models.CharField(blank=True, max_length=300)),
                ('hero_text_fa', models.TextField(blank=True)),
                ('hero_text_en', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('phone_url', models.CharField(blank=True, max_length=100)),
                ('location_fa', models.CharField(blank=True, max_length=300)),
                ('location_en', models.CharField(blank=True, max_length=300)),
                ('form_kicker_fa', models.CharField(blank=True, max_length=200)),
                ('form_kicker_en', models.CharField(blank=True, max_length=200)),
                ('form_title_fa', models.CharField(blank=True, max_length=300)),
                ('form_title_en', models.CharField(blank=True, max_length=300)),
                ('form_highlight_fa', models.CharField(blank=True, max_length=300)),
                ('form_highlight_en', models.CharField(blank=True, max_length=300)),
                ('form_text_fa', models.TextField(blank=True)),
                ('form_text_en', models.TextField(blank=True)),
                ('privacy_note_fa', models.TextField(blank=True)),
                ('privacy_note_en', models.TextField(blank=True)),
                ('join_kicker_fa', models.CharField(blank=True, max_length=200)),
                ('join_kicker_en', models.CharField(blank=True, max_length=200)),
                ('join_title_fa', models.CharField(blank=True, max_length=300)),
                ('join_title_en', models.CharField(blank=True, max_length=300)),
                ('join_text_fa', models.TextField(blank=True)),
                ('join_text_en', models.TextField(blank=True)),
                ('join_button_fa', models.CharField(blank=True, max_length=100)),
                ('join_button_en', models.CharField(blank=True, max_length=100)),
                ('email_button_fa', models.CharField(blank=True, max_length=100)),
                ('email_button_en', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
